version: '3.8'

services:
  db:
    image: postgres:15
    container_name: mrp_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: FactoryMrp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  api:
    build:
      context: .
      dockerfile: src/Mrp.Api/Dockerfile
    container_name: mrp_api
    depends_on:
      - db
    ports:
      - "5260:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=FactoryMrp;Username=postgres;Password=postgres
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  pgdata:
